import type { Metadata } from 'next';
import './globals.css';
import { GeolocationSearchProvider } from '@/utils/providers/GeolocationSearchContext';

export const metadata: Metadata = {
	title: 'Weather Application',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<GeolocationSearchProvider>
			<html lang='en'>
				<body className='antialiased'>{children}</body>
			</html>
		</GeolocationSearchProvider>
	);
}
